function options = get_options_(varargin)
%GET_OPTIONS_ Default option struct.
%
%    options = get_options_('param1', value1, ...)
%
% See also lda.estimate lda.infer
  options = struct(...
    'var_max_iter',    -1, ...
    'var_converged',   1e-6, ...
    'em_max_iter',     100, ...
    'em_convergence',  1e-4, ...
    'estimate_alpha',  true, ...
    'initial_alpha',   0.5, ...
    'num_topics',      8, ...
    'random_seed',     4357, ...
    'verbose',         true);
  fields = fieldnames(options);
  for i = 1:2:nargin
    index = find(strcmp(varargin{i}, fields));
    if ~isempty(index)
      options.(fields{index}) = varargin{i+1};
    end
  end
end